spring:
  application:
    name: wage-app

  r2dbc:
    url: r2dbc:postgres://${POSTGRES_URL:localhost:5434}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    default-schema: wage_app
    enabled: true
    drop-first: false
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5434}/${POSTGRES_DB:postgres}
    user: user
    password: password
    change-log: db/changelog/db-changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:WageApp}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:WageApp}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:backend-core}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:a79VFySQIX0oZ7YycmkbfC9ciXuJfJKD}
            authorization-grant-type: client_credentials

server:
  port: 8085


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

notification:
  telegram:
    bot:
      url: ${TELEGRAM_BOT_URL:http://localhost:8096}